WORKERS=2
IP_PREFIX="10.0.0."
IP_POSTFIX=10
Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-22.04"
    config.vm.box_check_update = true

    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"

    config.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get install bridge-utils -y
            apt-get install traceroute -y
            apt-get install net-tools -y
            apt-get install nodejs -y
            curl -L https://github.com/projectcalico/calico/releases/download/v3.24.5/calicoctl-linux-amd64 -o kubectl-calico
            chmod +x kubectl-calico
            mv kubectl-calico /usr/local/bin/
    SHELL

    config.vm.provision "shell", env: {"IP_PREFIX" => IP_PREFIX, "IP_POSTFIX" => IP_POSTFIX}, inline: <<-SHELL
        apt-get update -y
        echo "$IP_PREFIX$((IP_POSTFIX)) master-node" >> /etc/hosts
        echo "$IP_PREFIX$((IP_POSTFIX+1)) worker-node01" >> /etc/hosts
        echo "$IP_PREFIX$((IP_POSTFIX+2)) worker-node02" >> /etc/hosts
        echo "$IP_PREFIX$((IP_POSTFIX+2)) worker-node03" >> /etc/hosts
    SHELL

    config.vm.define "master" do |master|
        master.vm.hostname = "master-node"
        master.vm.network "private_network", ip: IP_PREFIX + "#{IP_POSTFIX}"
        master.vm.provider "virtualbox" do |vb|
            vb.memory = 4048
            vb.cpus = 2
        end
        master.vm.provision "shell", path: "scripts/common.sh"
        master.vm.provision "shell", path: "scripts/master.sh"
    end


    (1..WORKERS).each do |i|
        config.vm.define "node0#{i}" do |node|
            node.vm.hostname = "worker-node0#{i}"
            node.vm.network "private_network", ip: IP_PREFIX + "#{IP_POSTFIX + i}"
            node.vm.provider "virtualbox" do |vb|
                vb.memory = 1024
                vb.cpus = 1
            end
            node.vm.provision "shell", path: "scripts/common.sh"
            node.vm.provision "shell", path: "scripts/node.sh"
        end
    end

end
