# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus   = 2
    end

    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install bridge-utils
        apt-get install traceroute
        apt-get install net-tools
    SHELL

    config.vm.provision "shell", path: "scripts/setup-ns.sh"

end
